import type { MachineDetail } from 'src/services/machines';

/**
 * Fixtures shared by the component specs. A test spells out only what it is
 * about; the rest of the poste is this one, which has nothing to report.
 */

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

/** A healthy, fully inventoried poste — every finding off. */
export function machineDetail(overrides: Partial<MachineDetail> = {}): MachineDetail {
  return {
    id: 'm1',
    machine_uuid: 'uuid-1',
    hostname: 'PC-01',
    domain: 'CORP',
    location: null,
    room_id: null,
    room_name: null,
    building_id: null,
    building_name: null,
    room_location: null,
    location_mismatch: false,
    check_open: false,
    check_assigned_to: null,
    last_maintenance_at: null,
    maintenance_due_at: null,
    maintenance_state: 'ok',
    maintenance_owner: null,
    open_check: null,
    ad_distinguished_name: null,
    ad_ou: null,
    ad_ou_dn: null,
    ad_location: null,
    ip_address: '10.0.0.1',
    os_version: 'Windows 11',
    agent_version: '0.3.0',
    is_up_to_date: true,
    needs_verification: false,
    signature_version: '1.2.3',
    av_product_name: 'Windows Defender',
    av_product_enabled: true,
    av_product_signatures_up_to_date: true,
    av_product_is_defender: true,
    session_user_present: true,
    session_username: 'alice',
    wu_pending_count: 0,
    wu_reboot_required: false,
    hw_model: 'OptiPlex',
    ram_total_mb: 16289,
    system_volume_total_mb: 500_000,
    system_volume_free_mb: 250_000,
    last_seen: daysAgo(0),
    is_online: true,
    usage_hours: 12,
    usage_days: 7,
    mac_address: null,
    ip_prefix_length: 24,
    rtp_enabled: true,
    av_enabled: true,
    signature_last_updated: daysAgo(0),
    signature_age_days: 0,
    last_quick_scan: daysAgo(1),
    last_full_scan: daysAgo(5),
    running_mode: 'Normal',
    session_state: 'active',
    session_is_remote: false,
    wu_last_search: daysAgo(1),
    wu_last_install: daysAgo(3),
    pending_updates: [],
    machine_guid: null,
    smbios_uuid: null,
    tpm_ek_hash: null,
    token_revoked: false,
    first_seen: daysAgo(100),
    created_at: daysAgo(100),
    updated_at: daysAgo(0),
    hw_manufacturer: 'Dell',
    hw_serial: null,
    hw_chassis_type: 'desktop',
    hw_is_virtual: false,
    hw_hypervisor: null,
    mb_manufacturer: null,
    mb_model: null,
    mb_serial: null,
    bios_vendor: null,
    bios_version: null,
    bios_date: null,
    secure_boot: true,
    tpm_version: '2.0',
    cpu_model: 'i7',
    cpu_manufacturer: null,
    cpu_cores: 8,
    cpu_threads: 16,
    cpu_speed_mhz: null,
    cpu_count: 1,
    ram_slots_total: 2,
    ram_slots_used: 2,
    os_architecture: '64-bit',
    os_install_date: null,
    last_boot_time: null,
    inventory_last_seen: daysAgo(0),
    memory_modules: [],
    disks: [],
    volumes: [
      {
        id: 1,
        letter: 'C:',
        label: null,
        filesystem: 'NTFS',
        total_mb: 500_000,
        free_mb: 250_000,
        is_system: true,
        encryption_status: 'FullyEncrypted',
      },
    ],
    nics: [],
    gpus: [],
    software: [],
    agent_latest_version: '0.3.0',
    ...overrides,
  };
}
